import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedInfofieldWidget9.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedAvatarWidget8.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedRectangle335Widget.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedBottomnavWidget4.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedCNhnWidget.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedInfofieldWidget11.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedInfofieldWidget10.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedCnhWidget.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedModeLightTypeDefaultWidget4.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedRectangle330Widget6.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget1/generated/GeneratedBannerWidget1.dart';

/* Frame User Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserProfileWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 389.0,
                child: GeneratedRectangle330Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget4(),
              ),
              Positioned(
                left: 74.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 22.0,
                child: GeneratedCNhnWidget(),
              ),
              Positioned(
                left: 253.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 22.0,
                child: GeneratedCnhWidget(),
              ),
              Positioned(
                left: 193.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 3.0,
                child: GeneratedRectangle335Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 200.0,
                child: GeneratedBannerWidget1(),
              ),
              Positioned(
                left: 124.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 126.0,
                child: GeneratedAvatarWidget8(),
              )
            ]),
      ),
    ));
  }
}
