import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedGroup9827Widget9.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedBottomnavWidget30.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedModeLightTypeDefaultWidget57.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedMaskGroupWidget57.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedAnnouncementWidget122.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedAnnouncementWidget124.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedAnnouncementWidget126.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedThngbokhcWidget14.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedQuantrngWidget9.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedAnnouncementWidget118.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedAnnouncementWidget120.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedThngboWidget58.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget117/generated/GeneratedAnnouncementWidget125.dart';

/* Frame Announcement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementWidget117 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget57(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 26.0,
                child: GeneratedThngboWidget58(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedQuantrngWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget14(),
              ),
              Positioned(
                left: 323.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 12.0,
                child: GeneratedGroup9827Widget9(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget57(),
              ),
              Positioned(
                left: 20.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget118(),
              ),
              Positioned(
                left: 20.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget120(),
              ),
              Positioned(
                left: 20.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget122(),
              ),
              Positioned(
                left: 20.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget124(),
              ),
              Positioned(
                left: 20.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget125(),
              ),
              Positioned(
                left: 20.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget126(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget30(),
              )
            ]),
      ),
    ));
  }
}
