import 'package:flutter/material.dart';

/* Rectangle [App] Log in 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAppLogin1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 4096.0,
      height: 2489.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/8378b65e9b29450d9fac0f22b12479ec2a8766c7.png",
          color: null,
          fit: BoxFit.cover,
          width: 4096.0,
          height: 2489.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
