import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedAnnouncementWidget139.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedPaginationWidget31.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedNewsWidget34.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedThngboWidget65.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedMaskGroupWidget77.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedChomngbnnviakaResidentWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedMaskGroupWidget76.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedModeLightTypeDefaultWidget69.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedCard4Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedPaginationWidget30.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedCardNewsWidget14.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedBottomnavWidget36.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedFrameWidget39.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget25/generated/GeneratedDoneccondimentumnecmagnautpulvinarSuspendissepotentiMae17.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget25 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget69(),
              ),
              Positioned(
                left: 20.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 145.0,
                child: GeneratedCard4Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget139(),
              ),
              Positioned(
                left: 19.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 29.0,
                child: GeneratedNewsWidget34(),
              ),
              Positioned(
                left: 20.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 26.0,
                child: GeneratedThngboWidget65(),
              ),
              Positioned(
                left: 21.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 37.83237075805664,
                child: GeneratedMaskGroupWidget76(),
              ),
              Positioned(
                left: 310.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedFrameWidget39(),
              ),
              Positioned(
                left: 0.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 200.0,
                child: GeneratedMaskGroupWidget77(),
              ),
              Positioned(
                left: 160.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 8.0,
                child: GeneratedPaginationWidget30(),
              ),
              Positioned(
                left: 160.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 8.0,
                child: GeneratedPaginationWidget31(),
              ),
              Positioned(
                left: 36.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 26.0,
                child: GeneratedChomngbnnviakaResidentWidget17(),
              ),
              Positioned(
                left: 34.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 49.0,
                child:
                    GeneratedDoneccondimentumnecmagnautpulvinarSuspendissepotentiMae17(),
              ),
              Positioned(
                left: 20.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 278.0,
                child: GeneratedCardNewsWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget36(),
              )
            ]),
      ),
    ));
  }
}
