import 'package:flutter/material.dart';

/* Rectangle image 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage6Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 153.0,
      height: 112.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/4d75139c6a56f976a9f2d881ae1c8f4454cf5de4.png",
          color: null,
          fit: BoxFit.cover,
          width: 153.0,
          height: 112.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
