import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedAnnouncementWidget22.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedBottomnavWidget9.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedModeLightTypeDefaultWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedAnnouncementWidget20.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedQuantrngWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedGroup9827Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedAnnouncementWidget28.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedMaskGroupWidget10.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedAnnouncementWidget26.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedAnnouncementWidget24.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedThngbokhcWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedAnnouncementWidget27.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget19/generated/GeneratedThngboWidget20.dart';

/* Frame Announcement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementWidget19 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget8(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 26.0,
                child: GeneratedThngboWidget20(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedQuantrngWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget2(),
              ),
              Positioned(
                left: 323.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 12.0,
                child: GeneratedGroup9827Widget1(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget20(),
              ),
              Positioned(
                left: 20.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget22(),
              ),
              Positioned(
                left: 20.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget24(),
              ),
              Positioned(
                left: 20.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget26(),
              ),
              Positioned(
                left: 20.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget27(),
              ),
              Positioned(
                left: 20.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget28(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget9(),
              )
            ]),
      ),
    ));
  }
}
