import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/Generated6numberWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedMain1Widget7.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedModeLightTypeNumericWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedGroup9818Widget8.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/Generated6numberiputWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedStatusBarBaseDarkWidget14.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedCopyrightbyakaResidentWidget9.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedModeLightTypeDefaultWidget36.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedComponent8Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedMkhnghplWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedDefaultWidget14.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedFrame9838Widget8.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwrongwidget/generated/GeneratedButtonWidget17.dart';

/* Frame Sign in / PIN wrong
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninPINwrongWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 24.0,
                child: GeneratedDefaultWidget14(),
              ),
              Positioned(
                left: 48.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 44.0,
                child: GeneratedButtonWidget17(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget36(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget9(),
              ),
              Positioned(
                left: 48.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 0.00002522498652979266,
                child: GeneratedGroup9818Widget8(),
              ),
              Positioned(
                left: 48.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedFrame9838Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedModeLightTypeNumericWidget4(),
              ),
              Positioned(
                left: 14.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 24.0,
                child: GeneratedComponent8Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 50.0,
                child: Generated6numberiputWidget2(),
              ),
              Positioned(
                left: 48.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedMkhnghplWidget1(),
              ),
              Positioned(
                left: 90.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 100.0,
                child: GeneratedMain1Widget7(),
              ),
              Positioned(
                left: 62.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 24.0,
                child: Generated6numberWidget1(),
              )
            ]),
      ),
    ));
  }
}
