import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomedarkwidget/generated/GeneratedGroupWidget41.dart';
import 'package:flutterapp/project_20teamapp/generatedhomedarkwidget/generated/GeneratedIMG_3688Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomedarkwidget/generated/GeneratedControlsPaginationDotsLight5DotsWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomedarkwidget/generated/GeneratedThngtinmiWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomedarkwidget/generated/GeneratedOvalWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedhomedarkwidget/generated/GeneratedBitmapWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomedarkwidget/generated/GeneratedFrameWidget60.dart';
import 'package:flutterapp/project_20teamapp/generatedhomedarkwidget/generated/GeneratedControlsPaginationDotsDark3DotsWidget2.dart';

/* Frame HomeDark
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeDarkWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 0, 0, 0),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 297.0,
                child: GeneratedIMG_3688Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngtinmiWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBitmapWidget2(),
              ),
              Positioned(
                left: 88.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 20.0,
                child: GeneratedControlsPaginationDotsDark3DotsWidget2(),
              ),
              Positioned(
                left: 323.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedOvalWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedFrameWidget60(),
              ),
              Positioned(
                left: 16.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 88.0,
                child: GeneratedGroupWidget41(),
              ),
              Positioned(
                left: 88.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 20.0,
                child: GeneratedControlsPaginationDotsLight5DotsWidget1(),
              )
            ]),
      ),
    ));
  }
}
