import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget/generated/GeneratedFrame52Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget/generated/GeneratedBottomnavWidget13.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget/generated/GeneratedChititthngboWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget/generated/GeneratedThngbokhcWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget/generated/GeneratedModeLightTypeDefaultWidget11.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget/generated/GeneratedGroup9825Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget/generated/GeneratedMaskGroupWidget13.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget/generated/GeneratedBottomnavWidget12.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget/generated/GeneratedRectangle325Widget1.dart';

/* Frame Announcement details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementdetailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget11(),
              ),
              Positioned(
                left: -32.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 56.0,
                child: GeneratedRectangle325Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 26.0,
                child: GeneratedChititthngboWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 24.0,
                child: GeneratedFrame52Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.00003051757812,
                child: GeneratedGroup9825Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget12(),
              ),
              Positioned(
                left: 310.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget13(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget13(),
              )
            ]),
      ),
    ));
  }
}
