import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget36/generated/GeneratedBottomnavWidget11.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget36/generated/GeneratedMaskGroupWidget12.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget36/generated/GeneratedGroup9827Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget36/generated/GeneratedModeLightTypeDefaultWidget10.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget36/generated/GeneratedQuantrngWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget36/generated/GeneratedAnnouncementWidget37.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget36/generated/GeneratedThngbokhcWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget36/generated/GeneratedThngboWidget22.dart';

/* Frame Announcement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementWidget36 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 26.0,
                child: GeneratedThngboWidget22(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedQuantrngWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget4(),
              ),
              Positioned(
                left: 323.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 12.0,
                child: GeneratedGroup9827Widget3(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget12(),
              ),
              Positioned(
                left: 20.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 569.0,
                child: GeneratedAnnouncementWidget37(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget11(),
              )
            ]),
      ),
    ));
  }
}
