import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedModeLightTypeNumericWidget6.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedGroup9818Widget10.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedDefaultWidget16.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedFrame9838Widget10.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/Generated6numberiputWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedButtonWidget19.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedStatusBarBaseDarkWidget16.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedComponent8Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedMain1Widget9.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedModeLightTypeDefaultWidget38.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedMkhngtrngvimPINtrcWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwrongwidget/generated/GeneratedCopyrightbyakaResidentWidget11.dart';

/* Frame Sign in / PIN confirm wrong
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninPINconfirmwrongWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 24.0,
                child: GeneratedDefaultWidget16(),
              ),
              Positioned(
                left: 48.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 44.0,
                child: GeneratedButtonWidget19(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget38(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget11(),
              ),
              Positioned(
                left: 48.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 0.00002522498652979266,
                child: GeneratedGroup9818Widget10(),
              ),
              Positioned(
                left: 48.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedFrame9838Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedModeLightTypeNumericWidget6(),
              ),
              Positioned(
                left: 48.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 50.0,
                child: Generated6numberiputWidget4(),
              ),
              Positioned(
                left: 59.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 26.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 24.0,
                child: GeneratedComponent8Widget3(),
              ),
              Positioned(
                left: 48.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 26.0,
                child: GeneratedMkhngtrngvimPINtrcWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 100.0,
                child: GeneratedMain1Widget9(),
              )
            ]),
      ),
    ));
  }
}
