import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedModeLightTypeDefaultWidget24.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedAnnouncementWidget68.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedGroup9827Widget5.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedMaskGroupWidget29.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedThngbokhcWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedAnnouncementWidget65.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedAnnouncementWidget69.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedAnnouncementWidget67.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedBottomnavWidget18.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedThngboWidget35.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedQuantrngWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedAnnouncementWidget63.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget60/generated/GeneratedAnnouncementWidget61.dart';

/* Frame Announcement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementWidget60 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget24(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 26.0,
                child: GeneratedThngboWidget35(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedQuantrngWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget8(),
              ),
              Positioned(
                left: 323.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 12.0,
                child: GeneratedGroup9827Widget5(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget29(),
              ),
              Positioned(
                left: 20.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget61(),
              ),
              Positioned(
                left: 20.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget63(),
              ),
              Positioned(
                left: 20.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget65(),
              ),
              Positioned(
                left: 20.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget67(),
              ),
              Positioned(
                left: 20.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget68(),
              ),
              Positioned(
                left: 20.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget69(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget18(),
              )
            ]),
      ),
    ));
  }
}
