import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedDndpWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedPathWidget291.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedComponentsserviceWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedComponentsservicecopy4Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedComponentsservicecopyWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedComponentsservicecopy3Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedRectangleCopy2Widget5.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedRectangleCopyWidget15.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedComponentsservicecopy2Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedDchvWidget42.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedChnWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice1widget/generated/GeneratedFrameWidget65.dart';

/* Frame CleaningService1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCleaningService1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 95.0,
                child: GeneratedComponentsserviceWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 95.0,
                child: GeneratedComponentsservicecopyWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 95.0,
                child: GeneratedComponentsservicecopy2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 95.0,
                child: GeneratedComponentsservicecopy3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 95.0,
                child: GeneratedComponentsservicecopy4Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedRectangleCopyWidget15(),
              ),
              Positioned(
                left: 0.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedRectangleCopy2Widget5(),
              ),
              Positioned(
                left: 9.307611465454102,
                top: 62.5,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedPathWidget291(),
              ),
              Positioned(
                left: 26.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 21.0,
                child: GeneratedDchvWidget42(),
              ),
              Positioned(
                left: 153.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 22.0,
                child: GeneratedDndpWidget1(),
              ),
              Positioned(
                left: 320.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 24.0,
                child: GeneratedChnWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedFrameWidget65(),
              )
            ]),
      ),
    ));
  }
}
