import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generateddefaultwidget37/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/project_20teamapp/generateddefaultwidget37/generated/GeneratedComponent1Widget31.dart';

/* Group default
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDefaultWidget37 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 279.0,
      height: 79.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 49.0,
              height: 29.0,
              child: GeneratedPasswordWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 29.0,
              right: null,
              bottom: null,
              width: 279.0,
              height: 50.0,
              child: GeneratedComponent1Widget31(),
            )
          ]),
    ));
  }
}
