import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget3/generated/GeneratedGroup9838Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget3/generated/GeneratedTrliWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget3/generated/GeneratedGilimWidget6.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget3/generated/GeneratedCopyrightbyakaResidentWidget23.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget3/generated/GeneratedStatusBarBaseDarkWidget30.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget3/generated/GeneratedGroup9820Widget17.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget3/generated/GeneratedGroup9818Widget19.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget3/generated/GeneratedFrame9838Widget19.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget3/generated/GeneratedMaskGroupWidget65.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget3/generated/GeneratedModeLightTypeDefaultWidget62.dart';

/* Frame Sign in / OTP
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninOTPWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 194.0,
                child: GeneratedGroup9820Widget17(),
              ),
              Positioned(
                left: 48.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedGilimWidget6(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget30(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget62(),
              ),
              Positioned(
                left: 76.0,
                top: 125.20809936523438,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget65(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget23(),
              ),
              Positioned(
                left: 48.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 0.00002522498652979266,
                child: GeneratedGroup9818Widget19(),
              ),
              Positioned(
                left: 48.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedFrame9838Widget19(),
              ),
              Positioned(
                left: 43.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 20.512821197509766,
                height: 24.615385055541992,
                child: GeneratedGroup9838Widget3(),
              ),
              Positioned(
                left: 69.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 26.0,
                child: GeneratedTrliWidget2(),
              )
            ]),
      ),
    ));
  }
}
