import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedFrame54Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedGroup9826Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedFrame53Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedThngbokhcWidget19.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedRectangle325Widget6.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedThngboWidget71.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedQuantrngWidget12.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedGroup9825Widget6.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedBottomnavWidget38.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedGroup9827Widget12.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedFrameWidget45.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedGroup9836Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedGroup9824Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget141/generated/GeneratedModeLightTypeDefaultWidget71.dart';

/* Frame Announcement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementWidget141 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget71(),
              ),
              Positioned(
                left: -32.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 56.0,
                child: GeneratedRectangle325Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 26.0,
                child: GeneratedThngboWidget71(),
              ),
              Positioned(
                left: 20.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedQuantrngWidget12(),
              ),
              Positioned(
                left: -16.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 56.0,
                child: GeneratedGroup9836Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget19(),
              ),
              Positioned(
                left: 310.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedFrameWidget45(),
              ),
              Positioned(
                left: 0.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.00003051757812,
                child: GeneratedGroup9825Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.00003051757812,
                child: GeneratedGroup9826Widget(),
              ),
              Positioned(
                left: 323.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 12.0,
                child: GeneratedGroup9827Widget12(),
              ),
              Positioned(
                left: 0.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.00003051757812,
                child: GeneratedGroup9824Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 102.0,
                child: GeneratedFrame53Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 102.0,
                child: GeneratedFrame54Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget38(),
              )
            ]),
      ),
    ));
  }
}
