import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget796 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 40.0,
      height: 40.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M36 0L4 0C1.79 0 0.02 1.79 0.02 4L0 40L8 32L36 32C38.21 32 40 30.21 40 28L40 4C40 1.79 38.21 0 36 0ZM22 24L18 24L18 20L22 20L22 24ZM22 16L18 16L18 8L22 8L22 16Z')
          ..color = Color.fromARGB(255, 0, 0, 0),
      ]),
    ));
  }
}
