import 'package:flutter/material.dart';

/* Rectangle Rectangle 329
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle329Widget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 493.0751953125,
      height: 1075.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          color: Color.fromARGB(255, 196, 196, 196),
        ),
      ),
    ));
  }
}
