import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup1widget/generated/GeneratedHome1Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup1widget/generated/GeneratedHomeWidget30.dart';

/* Group Group 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 33.0,
      height: 44.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 4.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedHome1Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 30.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 19.0,
              child: GeneratedHomeWidget30(),
            )
          ]),
    ));
  }
}
