import 'package:flutter/material.dart';

/* Text Họ tên Số điện thoại Email
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHtnSinthoiEmailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: RichText(
            overflow: TextOverflow.visible,
            textAlign: TextAlign.left,
            text: const TextSpan(
              style: TextStyle(
                height: 1.4285714285714286,
                fontSize: 14.0,
                fontFamily: 'Roboto',
                fontWeight: FontWeight.w400,
                color: Color.fromARGB(255, 78, 78, 78),

                /* letterSpacing: 0.0, */
              ),
              children: [
                TextSpan(
                  text: '''Họ tên
''',
                  style: TextStyle(
                    height: 1.4285714285714286,
                    fontSize: 14.0,
                    fontFamily: 'Roboto',
                    fontWeight: FontWeight.w700,

                    /* letterSpacing: 0.0, */
                  ),
                )
              ],
            )));
  }
}
