import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedmain1widget13/generated/GeneratedLogomainWidget13.dart';

/* Frame main 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMain1Widget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 397.0,
        height: 202.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 7.999810695648193,
                top: 5.0,
                right: null,
                bottom: null,
                width: 386.8681945800781,
                height: 179.96800231933594,
                child: GeneratedLogomainWidget13(),
              )
            ]),
      ),
    ));
  }
}
