import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget19/generated/GeneratedCardNewsWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget19/generated/GeneratedNewsWidget23.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget19/generated/GeneratedBottomnavWidget26.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget19/generated/GeneratedQuicknavWidget10.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget19/generated/GeneratedRectangle330Widget18.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget19/generated/GeneratedModeLightTypeDefaultWidget52.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget19/generated/GeneratedHerobannerWidget12.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget19/generated/GeneratedAnnouncementWidget95.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget19/generated/GeneratedLogoWidget18.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget19/generated/GeneratedAvatarWidget23.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget19 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 389.0,
                child: GeneratedRectangle330Widget18(),
              ),
              Positioned(
                left: 20.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 24.0,
                child: GeneratedNewsWidget23(),
              ),
              Positioned(
                left: 20.0,
                top: 638.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 278.0,
                child: GeneratedCardNewsWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget26(),
              ),
              Positioned(
                left: -245.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 929.0,
                height: 159.0,
                child: GeneratedAnnouncementWidget95(),
              ),
              Positioned(
                left: 48.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 76.0,
                child: GeneratedQuicknavWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 210.0,
                child: GeneratedHerobannerWidget12(),
              ),
              Positioned(
                left: 21.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 37.83237075805664,
                child: GeneratedLogoWidget18(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedAvatarWidget23(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget52(),
              )
            ]),
      ),
    ));
  }
}
