import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedmain1widget/generated/GeneratedLogomainWidget.dart';

/* Frame main 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMain1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 197.0,
        height: 100.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 3.9697067737579346,
                top: 2.475247621536255,
                right: null,
                bottom: null,
                width: 77.0,
                height: 35.735172271728516,
                child: GeneratedLogomainWidget(),
              )
            ]),
      ),
    ));
  }
}
