import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget1/generated/GeneratedLoginformWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget1/generated/GeneratedModeLightTypeDefaultWidget30.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget1/generated/GeneratedFooterWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget1/generated/GeneratedMain1Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget1/generated/GeneratedStatusBarBaseDarkWidget8.dart';

/* Frame Sign in / phone
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninphoneWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 63.999996185302734,
                child: GeneratedFooterWidget(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget30(),
              ),
              Positioned(
                left: 90.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 100.0,
                child: GeneratedMain1Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 286.0,
                child: GeneratedLoginformWidget(),
              )
            ]),
      ),
    ));
  }
}
