import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedInfofieldWidget6.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedInfofieldWidget2.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedModeLightTypeDefaultWidget3.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedInfofieldWidget8.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedBottomnavWidget3.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedInfofieldWidget.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedInfofieldWidget5.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedInfofieldWidget1.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedAvatarWidget7.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedInfofieldWidget3.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedRectangle330Widget5.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedInfofieldWidget4.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedInfofieldWidget7.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedBannerWidget.dart';
import 'package:flutterapp/project_20teamapp/generateduserprofilewidget/generated/GeneratedControlsSegmentedControlLight2ButtonsWidget.dart';

/* Frame User Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 389.0,
                child: GeneratedRectangle330Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 32.0,
                child: GeneratedControlsSegmentedControlLight2ButtonsWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget7(),
              ),
              Positioned(
                left: 20.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 30.0,
                child: GeneratedInfofieldWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 200.0,
                child: GeneratedBannerWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 126.0,
                child: GeneratedAvatarWidget7(),
              )
            ]),
      ),
    ));
  }
}
