import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescreenwidget/generated/GeneratedAkaResidentWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescreenwidget/generated/GeneratedAvatarWidget6.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescreenwidget/generated/GeneratedRectangle330Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescreenwidget/generated/GeneratedQuicknavWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescreenwidget/generated/GeneratedModeLightTypeDefaultWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescreenwidget/generated/GeneratedBottomnavWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescreenwidget/generated/GeneratedHerobannerWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescreenwidget/generated/GeneratedGroup9863Widget.dart';

/* Frame Home-screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomescreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1831.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1831.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 389.0,
                              child: GeneratedRectangle330Widget4(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 403.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 76.0,
                              child: GeneratedQuicknavWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1761.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 70.0,
                              child: GeneratedBottomnavWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 375.0,
                              child: GeneratedHerobannerWidget3(),
                            ),
                            Positioned(
                              left: 315.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 44.0,
                              child: GeneratedAvatarWidget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child: GeneratedModeLightTypeDefaultWidget2(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 55.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 29.0,
                              child: GeneratedAkaResidentWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 191.0,
                              right: null,
                              bottom: null,
                              width: 196.50088500976562,
                              height: 147.85044860839844,
                              child: GeneratedGroup9863Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
