import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedModeLightTypeDefaultWidget22.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedBottomnavWidget16.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedLogoWidget12.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedGroup9862Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedLogoWidget13.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedNewsWidget14.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedQuicknavWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedRectangle330Widget13.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedAnnouncementWidget50.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedHerobannerWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedNewsWidget16.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedAvatarWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedAvatarWidget18.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget3/generated/GeneratedFollowupWidget3.dart';

/* Frame Home-long
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomelongWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1831.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1831.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 389.0,
                              child: GeneratedRectangle330Widget13(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 181.0,
                              child: GeneratedNewsWidget14(),
                            ),
                            Positioned(
                              left: -393.0,
                              top: 641.0,
                              right: null,
                              bottom: null,
                              width: 1162.0,
                              height: 652.0,
                              child: GeneratedNewsWidget16(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 342.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 76.0,
                              child: GeneratedQuicknavWidget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 210.0,
                              child: GeneratedHerobannerWidget8(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget12(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget13(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget17(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget18(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child: GeneratedModeLightTypeDefaultWidget22(),
                            ),
                            Positioned(
                              left: -245.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 929.0,
                              height: 159.0,
                              child: GeneratedAnnouncementWidget50(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1761.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 70.0,
                              child: GeneratedBottomnavWidget16(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 1580.0,
                              right: null,
                              bottom: null,
                              width: 256.8018798828125,
                              height: 146.0,
                              child: GeneratedGroup9862Widget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1150.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 405.0,
                              child: GeneratedFollowupWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
