import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget797 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 18.0,
      height: 23.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M17 0L1 0C0.4 0 0 0.4 0 1L0 23L3 21L6 23L9 21L12 23L15 21L18 23L18 1C18 0.4 17.6 0 17 0ZM14 17L10 17L10 13L14 13L14 17ZM14 10L4 10L4 8L14 8L14 10ZM14 6L4 6L4 4L14 4L14 6Z')
          ..color = Color.fromARGB(255, 135, 151, 238),
      ]),
    ));
  }
}
