import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatediconxwidget/generated/GeneratedLogomainWidget14.dart';

/* Frame IconX
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconXWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 512.0,
        height: 512.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 58.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 397.0,
                height: 192.0,
                child: GeneratedLogomainWidget14(),
              )
            ]),
      ),
    ));
  }
}
