import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget1/generated/GeneratedGilimWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget1/generated/GeneratedFrame9838Widget7.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget1/generated/GeneratedGroup9820Widget7.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget1/generated/GeneratedCopyrightbyakaResidentWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget1/generated/GeneratedModeLightTypeNumericWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget1/generated/GeneratedMain1Widget5.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget1/generated/GeneratedStatusBarBaseDarkWidget12.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget1/generated/GeneratedGroup9818Widget7.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget1/generated/GeneratedComponent8Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget1/generated/GeneratedModeLightTypeDefaultWidget34.dart';

/* Frame Sign in / OTP
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninOTPWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 194.0,
                child: GeneratedGroup9820Widget7(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget34(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget8(),
              ),
              Positioned(
                left: 48.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 0.00002522498652979266,
                child: GeneratedGroup9818Widget7(),
              ),
              Positioned(
                left: 48.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedFrame9838Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedModeLightTypeNumericWidget3(),
              ),
              Positioned(
                left: 14.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 24.0,
                child: GeneratedComponent8Widget(),
              ),
              Positioned(
                left: 90.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 100.0,
                child: GeneratedMain1Widget5(),
              ),
              Positioned(
                left: 48.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedGilimWidget3(),
              )
            ]),
      ),
    ));
  }
}
