import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedAvatarWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedLogoWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedNewsWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedNewsWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedGroup9862Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedBottomnavWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedModeLightTypeDefaultWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedAvatarWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedQuicknavWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedHerobannerWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedRectangle330Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongbakwidget/generated/GeneratedLogoWidget3.dart';

/* Frame Home-long-bak
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomelongbakWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1831.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1831.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 389.0,
                              child: GeneratedRectangle330Widget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 181.0,
                              child: GeneratedNewsWidget3(),
                            ),
                            Positioned(
                              left: -393.0,
                              top: 641.0,
                              right: null,
                              bottom: null,
                              width: 1162.0,
                              height: 652.0,
                              child: GeneratedNewsWidget5(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 342.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 76.0,
                              child: GeneratedQuicknavWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 210.0,
                              child: GeneratedHerobannerWidget2(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget2(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget3(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget4(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child: GeneratedModeLightTypeDefaultWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1761.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 70.0,
                              child: GeneratedBottomnavWidget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 1580.0,
                              right: null,
                              bottom: null,
                              width: 256.8018798828125,
                              height: 146.0,
                              child: GeneratedGroup9862Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
