import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedbillswidget/generated/GeneratedComponentsbillcardWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedbillswidget/generated/GeneratedTabstab1Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedbillswidget/generated/GeneratedFrameWidget63.dart';
import 'package:flutterapp/project_20teamapp/generatedbillswidget/generated/GeneratedOvalWidget9.dart';
import 'package:flutterapp/project_20teamapp/generatedbillswidget/generated/GeneratedComponentsbillcardcopyWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedbillswidget/generated/GeneratedHanWidget96.dart';
import 'package:flutterapp/project_20teamapp/generatedbillswidget/generated/GeneratedControlsSegmentedControlLight2ButtonsWidget1.dart';

/* Frame Bills
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBillsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 41.0,
                child: GeneratedHanWidget96(),
              ),
              Positioned(
                left: 16.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 353.0,
                child: GeneratedComponentsbillcardWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 353.0,
                child: GeneratedComponentsbillcardcopyWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 32.0,
                child: GeneratedControlsSegmentedControlLight2ButtonsWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 84.0,
                child: GeneratedTabstab1Widget4(),
              ),
              Positioned(
                left: 323.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedOvalWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedFrameWidget63(),
              )
            ]),
      ),
    ));
  }
}
