import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedcardstatuswidget4/generated/GeneratedAnnouncementWidget6.dart';

/* Group Card / status
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardstatusWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 335.0,
      height: 107.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 107.0,
              child: GeneratedAnnouncementWidget6(),
            )
          ]),
    ));
  }
}
