import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedNewsWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedAvatarWidget19.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedBottomnavWidget22.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedHerobannerWidget9.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedAvatarWidget20.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedRectangle330Widget15.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedQuicknavWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedLogoWidget15.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedModeLightTypeDefaultWidget28.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedLogoWidget14.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget14/generated/GeneratedAnnouncementWidget80.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 389.0,
                child: GeneratedRectangle330Widget15(),
              ),
              Positioned(
                left: 20.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 24.0,
                child: GeneratedNewsWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget22(),
              ),
              Positioned(
                left: -245.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 929.0,
                height: 159.0,
                child: GeneratedAnnouncementWidget80(),
              ),
              Positioned(
                left: 48.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 76.0,
                child: GeneratedQuicknavWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 210.0,
                child: GeneratedHerobannerWidget9(),
              ),
              Positioned(
                left: 21.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 37.83237075805664,
                child: GeneratedLogoWidget14(),
              ),
              Positioned(
                left: 21.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 37.83237075805664,
                child: GeneratedLogoWidget15(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedAvatarWidget19(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedAvatarWidget20(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget28(),
              )
            ]),
      ),
    ));
  }
}
