import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedloadingwidget/generated/GeneratedMaskGroupWidget15.dart';
import 'package:flutterapp/project_20teamapp/generatedloadingwidget/generated/GeneratedImage7Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedloadingwidget/generated/GeneratedCopyrightbyakaResidentWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedloadingwidget/generated/GeneratedModeLightTypeDefaultWidget13.dart';
import 'package:flutterapp/project_20teamapp/generatedloadingwidget/generated/GeneratedStatusBarBaseDarkWidget1.dart';

/* Frame loading
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoadingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 229, 176, 75),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget1(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget13(),
              ),
              Positioned(
                left: 76.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget15(),
              ),
              Positioned(
                left: 117.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 276.0,
                child: GeneratedImage7Widget(),
              )
            ]),
      ),
    ));
  }
}
