import 'package:flutter/material.dart';

/* Text đăng kí as cư dân: nhập số đt >> mapping với hệ thống webadmin >> checking phải cư dân >> gửi OTP >> Nhập OTP >> New pincode >> confirm pincode >> trang chủ
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedngkascdnnhpstmappingvihthngwebadmincheckingphicdngiOTPN
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''đăng kí as cư dân:
nhập số đt >> mapping với hệ thống webadmin >> checking phải cư dân >> gửi OTP >> Nhập OTP >> New pincode >> confirm pincode >> trang chủ''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.3333333333333333,
        fontSize: 30.0,
        fontFamily: 'Be Vietnam',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
