import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget23/generated/GeneratedLogoWidget21.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget23/generated/GeneratedCard4Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget23/generated/GeneratedBottomnavWidget34.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget23/generated/GeneratedMaskGroupWidget68.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget23/generated/GeneratedModeLightTypeDefaultWidget63.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget23/generated/GeneratedMaskGroupWidget67.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget23/generated/GeneratedNewsWidget31.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget23/generated/GeneratedHerobannerWidget15.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget23/generated/GeneratedAnnouncementWidget137.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget23/generated/GeneratedAvatarWidget26.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget23 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget63(),
              ),
              Positioned(
                left: 20.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 145.0,
                child: GeneratedCard4Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 210.0,
                child: GeneratedHerobannerWidget15(),
              ),
              Positioned(
                left: 19.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 318.0,
                child: GeneratedNewsWidget31(),
              ),
              Positioned(
                left: 20.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 24.0,
                child: GeneratedAnnouncementWidget137(),
              ),
              Positioned(
                left: 21.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 37.83237075805664,
                child: GeneratedMaskGroupWidget67(),
              ),
              Positioned(
                left: 21.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 37.83237075805664,
                child: GeneratedLogoWidget21(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget68(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedAvatarWidget26(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget34(),
              )
            ]),
      ),
    ));
  }
}
