import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generateda41widget/generated/GeneratedGroup9851Widget.dart';
import 'package:flutterapp/project_20teamapp/generateda41widget/generated/GeneratedAnnouncementWidget143.dart';
import 'package:flutterapp/project_20teamapp/generateda41widget/generated/GeneratedAnnouncementWidget142.dart';
import 'package:flutterapp/project_20teamapp/generateda41widget/generated/GeneratedGroup9848Widget.dart';

/* Frame A4 - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedA41Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 595.0,
        height: 842.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 181, 181, 181),
                ),
              ),
              Positioned(
                left: 31.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget142(),
              ),
              Positioned(
                left: 31.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget143(),
              ),
              Positioned(
                left: 31.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 100.0,
                child: GeneratedGroup9848Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 76.0,
                child: GeneratedGroup9851Widget(),
              )
            ]),
      ),
    ));
  }
}
