import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescrollupwidget/generated/GeneratedTabstab1Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescrollupwidget/generated/GeneratedGroup2Widget17.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescrollupwidget/generated/GeneratedAkaResidentWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescrollupwidget/generated/GeneratedGroupWidget42.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescrollupwidget/generated/GeneratedThngtinmiWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescrollupwidget/generated/GeneratedControlsPaginationDotsLight5DotsWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescrollupwidget/generated/GeneratedOvalWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescrollupwidget/generated/GeneratedFrameWidget61.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescrollupwidget/generated/GeneratedGroup2CopyWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomescrollupwidget/generated/GeneratedRectangleWidget246.dart';

/* Frame HomeScrollup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScrollupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 385.0,
                child: GeneratedGroup2Widget17(),
              ),
              Positioned(
                left: 16.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 404.0,
                child: GeneratedGroup2CopyWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngtinmiWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 88.0,
                child: GeneratedGroupWidget42(),
              ),
              Positioned(
                left: 88.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 20.0,
                child: GeneratedControlsPaginationDotsLight5DotsWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 96.0,
                child: GeneratedRectangleWidget246(),
              ),
              Positioned(
                left: 323.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedOvalWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 84.0,
                child: GeneratedTabstab1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedFrameWidget61(),
              ),
              Positioned(
                left: 16.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 29.0,
                child: GeneratedAkaResidentWidget3(),
              )
            ]),
      ),
    ));
  }
}
