import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedcardbillnotyetpaidwidget11/generated/GeneratedCardstatusWidget27.dart';
import 'package:flutterapp/project_20teamapp/generatedcardbillnotyetpaidwidget11/generated/GeneratedLinkrightWidget59.dart';

/* Group Card / bill / not yet paid
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardbillnotyetpaidWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 335.0,
      height: 95.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 95.0,
              child: GeneratedCardstatusWidget27(),
            ),
            Positioned(
              left: 241.0,
              top: 60.0,
              right: null,
              bottom: null,
              width: 77.0,
              height: 20.0,
              child: GeneratedLinkrightWidget59(),
            )
          ]),
    ));
  }
}
