import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget77/generated/GeneratedThngbokhcWidget10.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget77/generated/GeneratedQuantrngWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget77/generated/GeneratedGroup9827Widget7.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget77/generated/GeneratedModeLightTypeDefaultWidget26.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget77/generated/GeneratedThngboWidget37.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget77/generated/GeneratedAnnouncementWidget78.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget77/generated/GeneratedMaskGroupWidget31.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget77/generated/GeneratedBottomnavWidget20.dart';

/* Frame Announcement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementWidget77 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget26(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 26.0,
                child: GeneratedThngboWidget37(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedQuantrngWidget7(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget10(),
              ),
              Positioned(
                left: 323.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 12.0,
                child: GeneratedGroup9827Widget7(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget31(),
              ),
              Positioned(
                left: 20.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 569.0,
                child: GeneratedAnnouncementWidget78(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget20(),
              )
            ]),
      ),
    ));
  }
}
