import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget2/generated/GeneratedStatusBarBaseDarkWidget26.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget2/generated/GeneratedGroup9855Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget2/generated/GeneratedMaskGroupWidget44.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget2/generated/GeneratedGroup9820Widget14.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget2/generated/GeneratedButtonWidget28.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget2/generated/GeneratedCopyrightbyakaResidentWidget19.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget2/generated/GeneratedngktikhonmiWidget20.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget2/generated/GeneratedModeLightTypeDefaultWidget48.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget2/generated/GeneratedButtonWidget29.dart';

/* Frame Sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 968.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 968.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 306.0,
                              right: null,
                              bottom: null,
                              width: 279.0,
                              height: 310.0,
                              child: GeneratedGroup9820Widget14(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 912.0,
                              right: null,
                              bottom: null,
                              width: 282.0,
                              height: 26.0,
                              child: GeneratedCopyrightbyakaResidentWidget19(),
                            ),
                            Positioned(
                              left: -3198.0,
                              top: -101.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 67.0,
                              child: GeneratedStatusBarBaseDarkWidget26(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child: GeneratedModeLightTypeDefaultWidget48(),
                            ),
                            Positioned(
                              left: 76.0,
                              top: 125.20809936523438,
                              right: null,
                              bottom: null,
                              width: 221.0,
                              height: 108.58381652832031,
                              child: GeneratedMaskGroupWidget44(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 258.0,
                              right: null,
                              bottom: null,
                              width: 182.0,
                              height: 26.0,
                              child: GeneratedngktikhonmiWidget20(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 766.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 69.0,
                              child: GeneratedGroup9855Widget4(),
                            ),
                            Positioned(
                              left: 192.0,
                              top: 634.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 44.0,
                              child: GeneratedButtonWidget28(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 634.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 44.0,
                              child: GeneratedButtonWidget29(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
