import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedherobannerwidget1/generated/GeneratedMaskGroupWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedherobannerwidget1/generated/GeneratedDoneccondimentumnecmagnautpulvinarSuspendissepotentiMae1.dart';
import 'package:flutterapp/project_20teamapp/generatedherobannerwidget1/generated/GeneratedChomngbnnviakaResidentWidget1.dart';

/* Group hero banner
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHerobannerWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 310.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 310.0,
              child: GeneratedMaskGroupWidget1(),
            ),
            Positioned(
              left: 36.0,
              top: 125.0,
              right: null,
              bottom: null,
              width: 304.0,
              height: 21.0,
              child: GeneratedChomngbnnviakaResidentWidget1(),
            ),
            Positioned(
              left: 34.0,
              top: 160.90475463867188,
              right: null,
              bottom: null,
              width: 307.0,
              height: 71.38095092773438,
              child:
                  GeneratedDoneccondimentumnecmagnautpulvinarSuspendissepotentiMae1(),
            )
          ]),
    ));
  }
}
