import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwrongphonewidget/generated/GeneratedGroup9858Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwrongphonewidget/generated/GeneratedComponent7Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwrongphonewidget/generated/GeneratedGroup9820Widget5.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwrongphonewidget/generated/GeneratedSinthoikhnghplhocchangkWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwrongphonewidget/generated/GeneratedCopyrightbyakaResidentWidget6.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwrongphonewidget/generated/GeneratedModeLightTypeDefaultWidget18.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwrongphonewidget/generated/GeneratedStatusBarBaseDarkWidget6.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwrongphonewidget/generated/GeneratedNhpsphoneWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwrongphonewidget/generated/GeneratedMaskGroupWidget23.dart';

/* Frame Sign in / wrong phone
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninwrongphoneWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 173.0,
                child: GeneratedGroup9820Widget5(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget6(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget18(),
              ),
              Positioned(
                left: 76.0,
                top: 125.20809936523438,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget23(),
              ),
              Positioned(
                left: 48.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 26.0,
                child: GeneratedNhpsphoneWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 26.0,
                child: GeneratedSinthoikhnghplhocchangkWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 69.0,
                child: GeneratedGroup9858Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 24.0,
                child: GeneratedComponent7Widget(),
              )
            ]),
      ),
    ));
  }
}
