import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget4/generated/GeneratedModeLightTypeDefaultWidget44.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget4/generated/GeneratedMaskGroupWidget40.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget4/generated/GeneratedGroup9818Widget14.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget4/generated/GeneratedGroup9820Widget12.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget4/generated/GeneratedngktikhonmiWidget18.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget4/generated/GeneratedStatusBarBaseDarkWidget22.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget4/generated/GeneratedCopyrightbyakaResidentWidget15.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget4/generated/GeneratedNhpsphoneWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninphonewidget4/generated/GeneratedFrame9838Widget14.dart';

/* Frame Sign in / phone
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninphoneWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 173.0,
                child: GeneratedGroup9820Widget12(),
              ),
              Positioned(
                left: 47.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 0.00002522498652979266,
                child: GeneratedGroup9818Widget14(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget15(),
              ),
              Positioned(
                left: 47.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedFrame9838Widget14(),
              ),
              Positioned(
                left: 47.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedngktikhonmiWidget18(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget22(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget44(),
              ),
              Positioned(
                left: 76.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget40(),
              ),
              Positioned(
                left: 48.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 26.0,
                child: GeneratedNhpsphoneWidget4(),
              )
            ]),
      ),
    ));
  }
}
