import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9843widget/generated/GeneratedRectangle327Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9843widget/generated/GeneratedGroup9823Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9843widget/generated/GeneratedLine14Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9843widget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9843widget/generated/Generated1Widget10.dart';

/* Instance Group 9843
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup9843Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 107.00003051757812,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 107.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 1.0,
              child: GeneratedLine15Widget(),
            ),
            Positioned(
              left: 20.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 339.0,
              height: 70.0,
              child: GeneratedGroup9823Widget(),
            ),
            Positioned(
              left: 4.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 371.0,
              height: 1.0,
              child: GeneratedLine14Widget(),
            ),
            Positioned(
              left: 364.399658203125,
              top: 77.0,
              right: null,
              bottom: null,
              width: 8.600324630737305,
              height: 16.0,
              child: Generated1Widget10(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 4.0,
              height: 106.0,
              child: GeneratedRectangle327Widget(),
            )
          ]),
    ));
  }
}
