import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedGroup9850Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedAnnouncementWidget31.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedAnnouncementWidget32.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedGroup9849Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedThngboWidget21.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedAnnouncementWidget30.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedBottomnavWidget10.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedThngbokhcWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedQuantrngWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedCardstatusWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedMaskGroupWidget11.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedGroup9827Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget29/generated/GeneratedModeLightTypeDefaultWidget9.dart';

/* Frame Announcement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementWidget29 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 26.0,
                child: GeneratedThngboWidget21(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedQuantrngWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget3(),
              ),
              Positioned(
                left: 323.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 12.0,
                child: GeneratedGroup9827Widget2(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget11(),
              ),
              Positioned(
                left: 20.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget30(),
              ),
              Positioned(
                left: 20.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget31(),
              ),
              Positioned(
                left: 20.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget32(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 100.0,
                child: GeneratedCardstatusWidget8(),
              ),
              Positioned(
                left: 20.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 100.0,
                child: GeneratedGroup9849Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 100.0,
                child: GeneratedGroup9850Widget(),
              )
            ]),
      ),
    ));
  }
}
