import 'package:flutter/material.dart';

/* Rectangle image 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage6Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 399.0,
      height: 812.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/1752bdc2b4829d60dae48928a8864b4a28c44fde.png",
          color: null,
          fit: BoxFit.cover,
          width: 399.0,
          height: 812.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
