import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget/generated/GeneratedGroup9820Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget/generated/GeneratedGroup9818Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget/generated/GeneratedStatusBarBaseDarkWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget/generated/GeneratedCopyrightbyakaResidentWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget/generated/GeneratedFrame9838Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget/generated/GeneratedMaskGroupWidget19.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget/generated/GeneratedModeLightTypeDefaultWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget/generated/GeneratedGilimWidget2.dart';

/* Frame Sign in / OTP original
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninOTPoriginalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 194.0,
                child: GeneratedGroup9820Widget4(),
              ),
              Positioned(
                left: 48.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedGilimWidget2(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget17(),
              ),
              Positioned(
                left: 76.0,
                top: 115.2080078125,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget19(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget5(),
              ),
              Positioned(
                left: 48.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 0.00002522498652979266,
                child: GeneratedGroup9818Widget4(),
              ),
              Positioned(
                left: 48.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedFrame9838Widget4(),
              )
            ]),
      ),
    ));
  }
}
