import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedGroup9855Widget5.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedIcontoolWidget13.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedIcontextWidget13.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedCard5Widget.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedIconmessagesquare1Widget13.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedComponent4Widget.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedCard6Widget.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedComponent6Widget.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedIcontextWidget15.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedGroup9856Widget30.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedComponent5Widget.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedComponent1Widget34.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedCard7Widget8.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedIconcalendarWidget20.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedLinkrightWidget61.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedCard4Widget5.dart';
import 'package:flutterapp/project_20teamapp/generateda42widget/generated/GeneratedIcontextWidget14.dart';

/* Frame A4 - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedA42Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2192.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1666.0,
                      height: 2192.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 403.0,
                              top: 323.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 76.0,
                              child: GeneratedComponent5Widget(),
                            ),
                            Positioned(
                              left: 291.0,
                              top: 166.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 76.0,
                              child: GeneratedComponent4Widget(),
                            ),
                            Positioned(
                              left: 168.0,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 76.0,
                              child: GeneratedComponent1Widget34(),
                            ),
                            Positioned(
                              left: 198.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 76.0,
                              child: GeneratedIcontextWidget13(),
                            ),
                            Positioned(
                              left: 277.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 76.0,
                              child: GeneratedIcontextWidget14(),
                            ),
                            Positioned(
                              left: 125.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 76.0,
                              child: GeneratedIcontextWidget15(),
                            ),
                            Positioned(
                              left: 345.5,
                              top: 102.25,
                              right: null,
                              bottom: null,
                              width: 19.999998092651367,
                              height: 22.5,
                              child: GeneratedIconcalendarWidget20(),
                            ),
                            Positioned(
                              left: 295.0,
                              top: 106.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 27.0,
                              child: GeneratedIconmessagesquare1Widget13(),
                            ),
                            Positioned(
                              left: 250.0,
                              top: 104.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedIcontoolWidget13(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 145.0,
                              child: GeneratedCard4Widget5(),
                            ),
                            Positioned(
                              left: 462.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 117.0,
                              child: GeneratedCard6Widget(),
                            ),
                            Positioned(
                              left: 843.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 117.0,
                              child: GeneratedCard7Widget8(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 737.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 20.0,
                              child: GeneratedLinkrightWidget61(),
                            ),
                            Positioned(
                              left: 98.0,
                              top: 834.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 24.0,
                              child: GeneratedComponent6Widget(),
                            ),
                            Positioned(
                              left: 194.0,
                              top: 877.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 24.0,
                              child: GeneratedGroup9856Widget30(),
                            ),
                            Positioned(
                              left: 111.0,
                              top: 917.0,
                              right: null,
                              bottom: null,
                              width: 51.8018798828125,
                              height: 20.0,
                              child: GeneratedGroup9855Widget5(),
                            ),
                            Positioned(
                              left: 427.0,
                              top: 830.0,
                              right: null,
                              bottom: null,
                              width: 313.0,
                              height: 278.0,
                              child: GeneratedCard5Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
