import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedMaskGroupWidget80.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedBottomnavWidget40.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedCard4Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedModeLightTypeDefaultWidget74.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedGroup37Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedCardNewsWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedGroup9826Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedGroup9825Widget8.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedMaskGroupWidget81.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedFrameWidget56.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedThngboWidget78.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedChomngbnnviakaResidentWidget19.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedDoneccondimentumnecmagnautpulvinarSuspendissepotentiMae19.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedGroup9824Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget32/generated/GeneratedNewsWidget36.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget32 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 278.0,
                child: GeneratedCardNewsWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget74(),
              ),
              Positioned(
                left: 20.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 145.0,
                child: GeneratedCard4Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget40(),
              ),
              Positioned(
                left: -254.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 97.0,
                child: GeneratedGroup9825Widget8(),
              ),
              Positioned(
                left: 352.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 97.0,
                child: GeneratedGroup9826Widget1(),
              ),
              Positioned(
                left: 49.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 97.0,
                child: GeneratedGroup9824Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 29.0,
                child: GeneratedNewsWidget36(),
              ),
              Positioned(
                left: 20.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 26.0,
                child: GeneratedThngboWidget78(),
              ),
              Positioned(
                left: 21.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 37.83237075805664,
                child: GeneratedMaskGroupWidget80(),
              ),
              Positioned(
                left: 310.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedFrameWidget56(),
              ),
              Positioned(
                left: 0.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 200.0,
                child: GeneratedMaskGroupWidget81(),
              ),
              Positioned(
                left: 36.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 26.0,
                child: GeneratedChomngbnnviakaResidentWidget19(),
              ),
              Positioned(
                left: 160.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 8.0,
                child: GeneratedGroup37Widget4(),
              ),
              Positioned(
                left: 34.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 49.0,
                child:
                    GeneratedDoneccondimentumnecmagnautpulvinarSuspendissepotentiMae19(),
              )
            ]),
      ),
    ));
  }
}
