import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget1/generated/GeneratedGilimWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget1/generated/GeneratedGroup9818Widget22.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget1/generated/GeneratedGroup9820Widget20.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget1/generated/GeneratedngktikhonmiWidget27.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget1/generated/GeneratedLinhWidget22.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget1/generated/GeneratedModeLightTypeDefaultWidget67.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget1/generated/GeneratedStatusBarBaseDarkWidget33.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget1/generated/GeneratedMaskGroupWidget74.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget1/generated/GeneratedCopyrightbyakaResidentWidget26.dart';

/* Frame Sign in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 215, 215, 215),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 194.0,
                child: GeneratedGroup9820Widget20(),
              ),
              Positioned(
                left: 48.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 24.0,
                child: GeneratedGroup9818Widget22(),
              ),
              Positioned(
                left: 48.0,
                top: 665.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedngktikhonmiWidget27(),
              ),
              Positioned(
                left: 48.0,
                top: 638.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedLinhWidget22(),
              ),
              Positioned(
                left: 48.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedGilimWidget7(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget33(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget67(),
              ),
              Positioned(
                left: 76.0,
                top: 125.20809936523438,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget74(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget26(),
              )
            ]),
      ),
    ));
  }
}
