import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9839widget/generated/GeneratedGroup9838Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9839widget/generated/GeneratedEllipse19Widget2.dart';

/* Group Group 9839
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup9839Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 40.0,
      height: 40.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 40.0,
              height: 40.0,
              child: GeneratedEllipse19Widget2(),
            ),
            Positioned(
              left: 10.256410598754883,
              top: 7.179487228393555,
              right: null,
              bottom: null,
              width: 20.512821197509766,
              height: 24.615385055541992,
              child: GeneratedGroup9838Widget2(),
            )
          ]),
    ));
  }
}
