import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget2/generated/GeneratedCopyrightbyakaResidentWidget27.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget2/generated/GeneratedMaskGroupWidget75.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget2/generated/GeneratedLinhWidget23.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget2/generated/GeneratedGilimWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget2/generated/GeneratedModeLightTypeDefaultWidget68.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget2/generated/GeneratedngktikhonmiWidget28.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget2/generated/GeneratedGroup9818Widget23.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget2/generated/GeneratedStatusBarBaseDarkWidget34.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget2/generated/GeneratedGroup9820Widget21.dart';

/* Frame Sign in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 215, 215, 215),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 194.0,
                child: GeneratedGroup9820Widget21(),
              ),
              Positioned(
                left: 48.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 24.0,
                child: GeneratedGroup9818Widget23(),
              ),
              Positioned(
                left: 48.0,
                top: 665.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedngktikhonmiWidget28(),
              ),
              Positioned(
                left: 48.0,
                top: 638.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedLinhWidget23(),
              ),
              Positioned(
                left: 48.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedGilimWidget8(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget34(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget68(),
              ),
              Positioned(
                left: 76.0,
                top: 125.20809936523438,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget75(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget27(),
              )
            ]),
      ),
    ));
  }
}
