import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget/generated/GeneratedCopyrightbyakaResidentWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget/generated/GeneratedModeLightTypeDefaultWidget19.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget/generated/GeneratedMaskGroupWidget24.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget/generated/GeneratedngktikhonmiWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget/generated/GeneratedGroup9855Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget/generated/GeneratedStatusBarBaseDarkWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget/generated/GeneratedGroup9820Widget6.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget/generated/GeneratedButtonWidget6.dart';

/* Frame Sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 154.0,
                child: GeneratedGroup9820Widget6(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget19(),
              ),
              Positioned(
                left: 76.0,
                top: 125.20809936523438,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget24(),
              ),
              Positioned(
                left: 48.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 26.0,
                child: GeneratedngktikhonmiWidget7(),
              ),
              Positioned(
                left: 48.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 69.0,
                child: GeneratedGroup9855Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget7(),
              ),
              Positioned(
                left: 48.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 44.0,
                child: GeneratedButtonWidget6(),
              )
            ]),
      ),
    ));
  }
}
