import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedNhpsphoneWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedStatusBarBaseDarkWidget32.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedMaskGroupWidget73.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedGroup9818Widget21.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedModeLightTypeDefaultWidget66.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedLinhWidget21.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedForgotpasswordWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedngktikhonmiWidget26.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedCopyrightbyakaResidentWidget25.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedGroup9820Widget19.dart';
import 'package:flutterapp/project_20teamapp/generatedframewidget38/generated/GeneratedSinthoikhnghplhocchangkWidget2.dart';

/* Frame Frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrameWidget38 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 215, 215, 215),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 173.0,
                child: GeneratedGroup9820Widget19(),
              ),
              Positioned(
                left: 48.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 24.0,
                child: GeneratedGroup9818Widget21(),
              ),
              Positioned(
                left: 48.0,
                top: 665.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedngktikhonmiWidget26(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget25(),
              ),
              Positioned(
                left: 48.0,
                top: 638.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedLinhWidget21(),
              ),
              Positioned(
                left: 47.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedForgotpasswordWidget1(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget32(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget66(),
              ),
              Positioned(
                left: 76.0,
                top: 125.20809936523438,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget73(),
              ),
              Positioned(
                left: 48.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 26.0,
                child: GeneratedNhpsphoneWidget7(),
              ),
              Positioned(
                left: 48.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 26.0,
                child: GeneratedSinthoikhnghplhocchangkWidget2(),
              )
            ]),
      ),
    ));
  }
}
