import 'package:flutter/material.dart';

/* Text Resident
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedResidentWidget15 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Resident''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 0.5714285714285714,
        fontSize: 42.0,
        fontFamily: 'Be Vietnam',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
