import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedAvatarWidget16.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedLogoWidget10.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedAnnouncementWidget46.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedFollowupWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedRectangle330Widget11.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedLogoWidget11.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedBottomnavWidget15.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedHerobannerWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedNewsWidget13.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedQuicknavWidget6.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedNewsWidget11.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedModeLightTypeDefaultWidget21.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget2/generated/GeneratedAvatarWidget15.dart';

/* Frame Home-long
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomelongWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1657.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1657.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 389.0,
                              child: GeneratedRectangle330Widget11(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 181.0,
                              child: GeneratedNewsWidget11(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 318.0,
                              child: GeneratedNewsWidget13(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 76.0,
                              child: GeneratedQuicknavWidget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 210.0,
                              child: GeneratedHerobannerWidget7(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget10(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget11(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget15(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget16(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child: GeneratedModeLightTypeDefaultWidget21(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1150.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 361.0,
                              child: GeneratedFollowupWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1587.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 70.0,
                              child: GeneratedBottomnavWidget15(),
                            ),
                            Positioned(
                              left: -245.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 929.0,
                              height: 159.0,
                              child: GeneratedAnnouncementWidget46(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
