import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninsignupwidget/generated/GeneratedMaskGroupWidget43.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninsignupwidget/generated/GeneratedGroup9820Widget13.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninsignupwidget/generated/GeneratedStatusBarBaseDarkWidget25.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninsignupwidget/generated/GeneratedModeLightTypeDefaultWidget47.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninsignupwidget/generated/GeneratedCopyrightbyakaResidentWidget18.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninsignupwidget/generated/GeneratedSinthoikhnghplhocchangkWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninsignupwidget/generated/GeneratedFrame9838Widget15.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninsignupwidget/generated/GeneratedGroup9818Widget15.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninsignupwidget/generated/GeneratedNhpsphoneWidget5.dart';

/* Frame Sign in / Sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninSignupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 173.0,
                child: GeneratedGroup9820Widget13(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget18(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget25(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget47(),
              ),
              Positioned(
                left: 76.0,
                top: 125.20809936523438,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget43(),
              ),
              Positioned(
                left: 48.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 26.0,
                child: GeneratedNhpsphoneWidget5(),
              ),
              Positioned(
                left: 48.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 26.0,
                child: GeneratedSinthoikhnghplhocchangkWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 0.00002522498652979266,
                child: GeneratedGroup9818Widget15(),
              ),
              Positioned(
                left: 48.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedFrame9838Widget15(),
              )
            ]),
      ),
    ));
  }
}
