import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget2/generated/GeneratedFrame52Widget5.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget2/generated/GeneratedRectangle325Widget5.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget2/generated/GeneratedThngbokhcWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget2/generated/GeneratedBottomnavWidget33.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget2/generated/GeneratedModeLightTypeDefaultWidget60.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget2/generated/GeneratedGroup9825Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget2/generated/GeneratedMaskGroupWidget60.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget2/generated/GeneratedChititthngboWidget2.dart';

/* Frame Announcement details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementdetailsWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget60(),
              ),
              Positioned(
                left: -32.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 56.0,
                child: GeneratedRectangle325Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 26.0,
                child: GeneratedChititthngboWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget17(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 24.0,
                child: GeneratedFrame52Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.00003051757812,
                child: GeneratedGroup9825Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget33(),
              ),
              Positioned(
                left: 310.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget60(),
              )
            ]),
      ),
    ));
  }
}
