import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9853widget/generated/GeneratedHanWidget90.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9853widget/generated/GeneratedEllipse20Widget59.dart';

/* Instance Group 9853
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup9853Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 52.0,
      height: 76.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 52.0,
              height: 52.0,
              child: GeneratedEllipse20Widget59(),
            ),
            Positioned(
              left: 3.0,
              top: 52.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 26.0,
              child: GeneratedHanWidget90(),
            )
          ]),
    ));
  }
}
