import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedThngbokhcWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedBottomnavWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedGroup9844Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedGroup9843Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedQuantrngWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedRectangle325Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedModeLightTypeDefaultWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedGroup9846Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedBottomnavWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedThngboWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedGroup9836Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedGroup9847Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedMaskGroupWidget9.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedGroup9827Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget18/generated/GeneratedGroup9845Widget.dart';

/* Frame Announcement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementWidget18 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget7(),
              ),
              Positioned(
                left: -32.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 56.0,
                child: GeneratedRectangle325Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 26.0,
                child: GeneratedThngboWidget17(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedQuantrngWidget(),
              ),
              Positioned(
                left: -16.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 56.0,
                child: GeneratedGroup9836Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget1(),
              ),
              Positioned(
                left: 338.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 12.0,
                child: GeneratedGroup9827Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 107.00003051757812,
                child: GeneratedGroup9843Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 107.00003051757812,
                child: GeneratedGroup9844Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 107.00003051757812,
                child: GeneratedGroup9846Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 107.00003051757812,
                child: GeneratedGroup9845Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 107.00003051757812,
                child: GeneratedGroup9847Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget7(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget8(),
              )
            ]),
      ),
    ));
  }
}
