import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget3/generated/GeneratedFrameWidget48.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget3/generated/GeneratedFrame52Widget7.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget3/generated/GeneratedChititthngboWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget3/generated/GeneratedBottomnavWidget39.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget3/generated/GeneratedGroup9825Widget7.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget3/generated/GeneratedThngbokhcWidget20.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget3/generated/GeneratedGroup9824Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget3/generated/GeneratedRectangle325Widget7.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementdetailswidget3/generated/GeneratedModeLightTypeDefaultWidget72.dart';

/* Frame Announcement details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementdetailsWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget72(),
              ),
              Positioned(
                left: -32.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 56.0,
                child: GeneratedRectangle325Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 26.0,
                child: GeneratedChititthngboWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget20(),
              ),
              Positioned(
                left: 310.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedFrameWidget48(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget39(),
              ),
              Positioned(
                left: 0.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.00003051757812,
                child: GeneratedGroup9824Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 24.0,
                child: GeneratedFrame52Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.00003051757812,
                child: GeneratedGroup9825Widget7(),
              )
            ]),
      ),
    ));
  }
}
