import 'package:flutter/material.dart';

/* Rectangle Home 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 896.447998046875,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/ee67408f8d192bd37b920724712c928b2ed1b21e.png",
          color: null,
          fit: BoxFit.cover,
          width: 414.0,
          height: 896.447998046875,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
