import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget/generated/GeneratedModeLightTypeDefaultWidget65.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget/generated/GeneratedLinhWidget20.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget/generated/GeneratedForgotpasswordWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget/generated/GeneratedGroup9818Widget20.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget/generated/GeneratedngktikhonmiWidget25.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget/generated/GeneratedMaskGroupWidget72.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget/generated/GeneratedStatusBarBaseDarkWidget31.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget/generated/GeneratedCopyrightbyakaResidentWidget24.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget/generated/GeneratedGroup9820Widget18.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwidget/generated/GeneratedNhpsphoneWidget6.dart';

/* Frame Sign in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 215, 215, 215),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 173.0,
                child: GeneratedGroup9820Widget18(),
              ),
              Positioned(
                left: 48.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 24.0,
                child: GeneratedGroup9818Widget20(),
              ),
              Positioned(
                left: 48.0,
                top: 665.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedngktikhonmiWidget25(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget24(),
              ),
              Positioned(
                left: 48.0,
                top: 638.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedLinhWidget20(),
              ),
              Positioned(
                left: 47.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedForgotpasswordWidget(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget31(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget65(),
              ),
              Positioned(
                left: 76.0,
                top: 125.20809936523438,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget72(),
              ),
              Positioned(
                left: 48.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 26.0,
                child: GeneratedNhpsphoneWidget6(),
              )
            ]),
      ),
    ));
  }
}
