import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget17/generated/GeneratedMaskGroupWidget48.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget17/generated/GeneratedHerobannerWidget11.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget17/generated/GeneratedNewsWidget21.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget17/generated/GeneratedCard4Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget17/generated/GeneratedAnnouncementWidget91.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget17/generated/GeneratedBottomnavWidget24.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget17/generated/GeneratedMaskGroupWidget49.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget17/generated/GeneratedModeLightTypeDefaultWidget51.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget17 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget51(),
              ),
              Positioned(
                left: 20.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 145.0,
                child: GeneratedCard4Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 210.0,
                child: GeneratedHerobannerWidget11(),
              ),
              Positioned(
                left: 19.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 318.0,
                child: GeneratedNewsWidget21(),
              ),
              Positioned(
                left: -245.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 929.0,
                height: 160.0,
                child: GeneratedAnnouncementWidget91(),
              ),
              Positioned(
                left: 21.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 37.83237075805664,
                child: GeneratedMaskGroupWidget48(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget49(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget24(),
              )
            ]),
      ),
    ));
  }
}
