import 'package:flutter/material.dart';

/* Rectangle [App] User Profile 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAppUserProfile1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1922.0,
      height: 1176.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/7d1c86c7f215b10d56d076b71c9f42230b744978.png",
          color: null,
          fit: BoxFit.cover,
          width: 1922.0,
          height: 1176.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
