import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedmorewidget/generated/GeneratedOvalWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedmorewidget/generated/GeneratedGroupWidget62.dart';
import 'package:flutterapp/project_20teamapp/generatedmorewidget/generated/GeneratedAkaResidentWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedmorewidget/generated/GeneratedFrameWidget67.dart';
import 'package:flutterapp/project_20teamapp/generatedmorewidget/generated/GeneratedVersion10MtsnWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedmorewidget/generated/GeneratedGroupCopyWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedmorewidget/generated/GeneratedThmWidget31.dart';
import 'package:flutterapp/project_20teamapp/generatedmorewidget/generated/GeneratedTabstab1Widget6.dart';

/* Frame More
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMoreWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 44.0,
                child: GeneratedThmWidget31(),
              ),
              Positioned(
                left: 0.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 84.0,
                child: GeneratedTabstab1Widget6(),
              ),
              Positioned(
                left: 323.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedOvalWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedFrameWidget67(),
              ),
              Positioned(
                left: 80.5,
                top: 597.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 82.0,
                child: GeneratedVersion10MtsnWidget(),
              ),
              Positioned(
                left: 134.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 29.0,
                child: GeneratedAkaResidentWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 163.0,
                child: GeneratedGroupWidget62(),
              ),
              Positioned(
                left: 0.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 207.0,
                child: GeneratedGroupCopyWidget4(),
              )
            ]),
      ),
    ));
  }
}
