import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedmodedarktypedefaultwidget/generated/GeneratedIPhoneXornewerWidget.dart';

/* Component Mode=Dark, Type=Default
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedModeDarkTypeDefaultWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 44.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedIPhoneXornewerWidget(),
            )
          ]),
    ));
  }
}
