import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedModeLightTypeDefaultWidget25.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedMaskGroupWidget30.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedAnnouncementWidget71.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedAnnouncementWidget73.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedThngboWidget36.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedGroup9827Widget6.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedThngbokhcWidget9.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedCardstatusWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedAnnouncementWidget72.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedGroup9849Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedBottomnavWidget19.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedQuantrngWidget6.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget70/generated/GeneratedGroup9850Widget1.dart';

/* Frame Announcement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementWidget70 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget25(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 26.0,
                child: GeneratedThngboWidget36(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedQuantrngWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget9(),
              ),
              Positioned(
                left: 323.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 12.0,
                child: GeneratedGroup9827Widget6(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget30(),
              ),
              Positioned(
                left: 20.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget71(),
              ),
              Positioned(
                left: 20.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget72(),
              ),
              Positioned(
                left: 20.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 101.0,
                child: GeneratedAnnouncementWidget73(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget19(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 100.0,
                child: GeneratedCardstatusWidget17(),
              ),
              Positioned(
                left: 20.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 100.0,
                child: GeneratedGroup9849Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 100.0,
                child: GeneratedGroup9850Widget1(),
              )
            ]),
      ),
    ));
  }
}
