import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget35/generated/GeneratedOvalWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget35/generated/GeneratedFrameWidget59.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget35/generated/GeneratedBitmapWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget35/generated/GeneratedThngtinmiWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget35/generated/GeneratedControlsPaginationDotsDark3DotsWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget35/generated/GeneratedControlsPaginationDotsLight5DotsWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget35/generated/GeneratedIMG_3688Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget35/generated/GeneratedGroupWidget40.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget35 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 297.0,
                child: GeneratedIMG_3688Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngtinmiWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBitmapWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 20.0,
                child: GeneratedControlsPaginationDotsDark3DotsWidget1(),
              ),
              Positioned(
                left: 323.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedOvalWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedFrameWidget59(),
              ),
              Positioned(
                left: 16.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 88.0,
                child: GeneratedGroupWidget40(),
              ),
              Positioned(
                left: 88.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 20.0,
                child: GeneratedControlsPaginationDotsLight5DotsWidget(),
              )
            ]),
      ),
    ));
  }
}
