import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Rectangle 330 (Stroke)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle330StrokeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 389.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M359 1L16 1C7.71573 1 1 7.71572 1 16L1 388L374 388L374 16C374 7.71573 367.284 1 359 1ZM16 0C7.16344 0 0 7.16343 0 16L0 389L375 389L375 16C375 7.16344 367.837 0 359 0L16 0Z')
          ..color = Color.fromARGB(255, 196, 196, 196),
      ]),
    ));
  }
}
