import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedModeLightTypeDefaultWidget64.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedNewsWidget33.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedChomngbnnviakaResidentWidget16.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedDoneccondimentumnecmagnautpulvinarSuspendissepotentiMae16.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedAvatarWidget27.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedCardNewsWidget13.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedMaskGroupWidget69.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedGroup9825Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedGroup37Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedLogoWidget22.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedAnnouncementWidget138.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedMaskGroupWidget71.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedThngboWidget64.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedMaskGroupWidget70.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget8/generated/GeneratedCard3Widget1.dart';

/* Frame Home long
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomelongWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1069.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1069.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child: GeneratedModeLightTypeDefaultWidget64(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 497.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 29.0,
                              child: GeneratedNewsWidget33(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 328.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 26.0,
                              child: GeneratedThngboWidget64(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 55.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedMaskGroupWidget69(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget22(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 200.0,
                              child: GeneratedMaskGroupWidget70(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 477.0,
                              right: null,
                              bottom: null,
                              width: 56.0,
                              height: 8.0,
                              child: GeneratedGroup9825Widget4(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 288.0,
                              right: null,
                              bottom: null,
                              width: 56.0,
                              height: 8.0,
                              child: GeneratedGroup37Widget1(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 185.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 26.0,
                              child: GeneratedChomngbnnviakaResidentWidget16(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 209.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 49.0,
                              child:
                                  GeneratedDoneccondimentumnecmagnautpulvinarSuspendissepotentiMae16(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 537.0,
                              right: null,
                              bottom: null,
                              width: 313.0,
                              height: 278.0,
                              child: GeneratedCardNewsWidget13(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 831.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 148.0,
                              child: GeneratedCard3Widget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 360.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 101.0,
                              child: GeneratedAnnouncementWidget138(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedMaskGroupWidget71(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget27(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
