import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwidget/generated/GeneratedStatusBarBaseDarkWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwidget/generated/GeneratedModeLightTypeNumericWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwidget/generated/GeneratedGilimWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwidget/generated/GeneratedGroup9818Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwidget/generated/GeneratedMaskGroupWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwidget/generated/GeneratedGroup9820Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwidget/generated/GeneratedCopyrightbyakaResidentWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwidget/generated/GeneratedModeLightTypeDefaultWidget15.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinwidget/generated/GeneratedFrame9838Widget2.dart';

/* Frame Sign in / PIN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninPINWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 194.0,
                child: GeneratedGroup9820Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedGilimWidget1(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget15(),
              ),
              Positioned(
                left: 76.0,
                top: 115.2080078125,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget17(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget3(),
              ),
              Positioned(
                left: 48.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 0.00002522498652979266,
                child: GeneratedGroup9818Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedFrame9838Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedModeLightTypeNumericWidget1(),
              )
            ]),
      ),
    ));
  }
}
