import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget31/generated/GeneratedModeLightTypeDefaultWidget73.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget31/generated/GeneratedCard4Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget31/generated/GeneratedImage2Widget19.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget31/generated/GeneratedGroup47Widget20.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget31/generated/GeneratedGroup37Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget31/generated/GeneratedFrameWidget53.dart';
import 'package:flutterapp/project_20teamapp/generatedhomewidget31/generated/GeneratedCardNewsWidget16.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget31 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 239, 239, 239),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 278.0,
                child: GeneratedCardNewsWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget73(),
              ),
              Positioned(
                left: 20.0,
                top: 684.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 145.0,
                child: GeneratedCard4Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 239.0,
                child: GeneratedGroup47Widget20(),
              ),
              Positioned(
                left: -169.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 834.0,
                height: 468.0,
                child: GeneratedImage2Widget19(),
              ),
              Positioned(
                left: 157.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 8.0,
                child: GeneratedGroup37Widget3(),
              ),
              Positioned(
                left: 310.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedFrameWidget53(),
              )
            ]),
      ),
    ));
  }
}
