import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwidget1/generated/GeneratedStatusBarBaseDarkWidget15.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwidget1/generated/Generated6numberiputWidget3.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwidget1/generated/GeneratedModeLightTypeNumericWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwidget1/generated/GeneratedModeLightTypeDefaultWidget37.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwidget1/generated/GeneratedGroup9818Widget9.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwidget1/generated/GeneratedMain1Widget8.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwidget1/generated/GeneratedCopyrightbyakaResidentWidget10.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwidget1/generated/GeneratedFrame9838Widget9.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwidget1/generated/GeneratedDefaultWidget15.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninpinconfirmwidget1/generated/GeneratedButtonWidget18.dart';

/* Frame Sign in / PIN confirm
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninPINconfirmWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 24.0,
                child: GeneratedDefaultWidget15(),
              ),
              Positioned(
                left: 48.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 44.0,
                child: GeneratedButtonWidget18(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget15(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget37(),
              ),
              Positioned(
                left: 90.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 100.0,
                child: GeneratedMain1Widget8(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget10(),
              ),
              Positioned(
                left: 48.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 0.00002522498652979266,
                child: GeneratedGroup9818Widget9(),
              ),
              Positioned(
                left: 48.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedFrame9838Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedModeLightTypeNumericWidget5(),
              ),
              Positioned(
                left: 48.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 50.0,
                child: Generated6numberiputWidget3(),
              )
            ]),
      ),
    ));
  }
}
