import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedavatarwidget2/generated/GeneratedEllipse18Widget2.dart';

/* Group avatar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAvatarWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 45.0,
      height: 45.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 45.0,
              height: 45.0,
              child: GeneratedEllipse18Widget2(),
            )
          ]),
    ));
  }
}
