import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedFollowupWidget6.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedHerobannerWidget14.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedQuicknavWidget12.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedAvatarWidget25.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedNewsWidget29.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedRectangle330Widget20.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedLogoWidget20.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedAnnouncementWidget109.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedModeLightTypeDefaultWidget54.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedNewsWidget27.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget6/generated/GeneratedBottomnavWidget28.dart';

/* Frame Home-long
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomelongWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1657.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1657.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 389.0,
                              child: GeneratedRectangle330Widget20(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 181.0,
                              child: GeneratedNewsWidget27(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 318.0,
                              child: GeneratedNewsWidget29(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 76.0,
                              child: GeneratedQuicknavWidget12(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 210.0,
                              child: GeneratedHerobannerWidget14(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget20(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget25(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child: GeneratedModeLightTypeDefaultWidget54(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1150.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 361.0,
                              child: GeneratedFollowupWidget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1587.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 70.0,
                              child: GeneratedBottomnavWidget28(),
                            ),
                            Positioned(
                              left: -245.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 929.0,
                              height: 159.0,
                              child: GeneratedAnnouncementWidget109(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
