import 'package:flutter/material.dart';

/* Rectangle Rectangle 327
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle327Widget22 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 4.0,
        height: 106.00000762939453,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 229, 176, 75),
          ),
        ),
      ),
    ));
  }
}
