import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedFollowupWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedModeLightTypeDefaultWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedNewsWidget6.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedAvatarWidget9.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedRectangle330Widget7.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedLogoWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedAvatarWidget10.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedNewsWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedLogoWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedHerobannerWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedAnnouncementWidget10.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedBottomnavWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget1/generated/GeneratedQuicknavWidget3.dart';

/* Frame Home-long
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomelongWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1657.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1657.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 389.0,
                              child: GeneratedRectangle330Widget7(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 181.0,
                              child: GeneratedNewsWidget6(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 318.0,
                              child: GeneratedNewsWidget8(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 76.0,
                              child: GeneratedQuicknavWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 210.0,
                              child: GeneratedHerobannerWidget4(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget4(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget5(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget9(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget10(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child: GeneratedModeLightTypeDefaultWidget5(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1150.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 361.0,
                              child: GeneratedFollowupWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1587.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 70.0,
                              child: GeneratedBottomnavWidget5(),
                            ),
                            Positioned(
                              left: -245.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 929.0,
                              height: 159.0,
                              child: GeneratedAnnouncementWidget10(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
