import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget1/generated/GeneratedButtonWidget23.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget1/generated/GeneratedGroup9820Widget9.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget1/generated/GeneratedFooterWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget1/generated/GeneratedModeLightTypeDefaultWidget41.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget1/generated/GeneratedComponent8Widget6.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget1/generated/GeneratedMain1Widget12.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget1/generated/GeneratedStatusBarBaseDarkWidget19.dart';
import 'package:flutterapp/project_20teamapp/generatedsignupwidget1/generated/GeneratedngktikhonmiWidget13.dart';

/* Frame Sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 260.0,
                child: GeneratedGroup9820Widget9(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget41(),
              ),
              Positioned(
                left: 90.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 100.0,
                child: GeneratedMain1Widget12(),
              ),
              Positioned(
                left: 48.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 26.0,
                child: GeneratedngktikhonmiWidget13(),
              ),
              Positioned(
                left: 48.0,
                top: 624.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 44.0,
                child: GeneratedButtonWidget23(),
              ),
              Positioned(
                left: 14.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 24.0,
                child: GeneratedComponent8Widget6(),
              ),
              Positioned(
                left: 48.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 63.999996185302734,
                child: GeneratedFooterWidget7(),
              )
            ]),
      ),
    ));
  }
}
