import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedFrameWidget66.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedComponentsservicecopy3Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedGroup4Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedComponentsservicecopyWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedRectangleCopyWidget21.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedComponentsservicecopy4Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedDndpWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedPathWidget297.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedChnWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedRectangleCopy2Widget6.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedDchvWidget43.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedViewsxOverlaysLightWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedComponentsservicecopy2Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedcleaningservice2widget/generated/GeneratedComponentsserviceWidget1.dart';

/* Frame CleaningService2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCleaningService2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 95.0,
                child: GeneratedComponentsserviceWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 95.0,
                child: GeneratedComponentsservicecopyWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 95.0,
                child: GeneratedComponentsservicecopy2Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 95.0,
                child: GeneratedComponentsservicecopy3Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 95.0,
                child: GeneratedComponentsservicecopy4Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedRectangleCopyWidget21(),
              ),
              Positioned(
                left: 0.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedRectangleCopy2Widget6(),
              ),
              Positioned(
                left: 9.307611465454102,
                top: 62.5,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedPathWidget297(),
              ),
              Positioned(
                left: 26.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 21.0,
                child: GeneratedDchvWidget43(),
              ),
              Positioned(
                left: 155.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 22.0,
                child: GeneratedDndpWidget2(),
              ),
              Positioned(
                left: 320.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 24.0,
                child: GeneratedChnWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedFrameWidget66(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedViewsxOverlaysLightWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 526.0,
                child: GeneratedGroup4Widget3(),
              )
            ]),
      ),
    ));
  }
}
