import 'package:flutter/material.dart';

/* Text TheTalkingBooks is opening a contest this week. You can find more about this reading contest and apply for it. Many rewards are available!
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTheTalkingBooksisopeningacontestthisweekYoucanfindmorea
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''TheTalkingBooks is opening a contest this week. You can find more about this reading contest and apply for it. Many rewards are available!''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.4,
        fontSize: 10.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 85, 85, 85),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
