import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget/generated/GeneratedModeLightTypeDefaultWidget14.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget/generated/GeneratedGroup9820Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget/generated/GeneratedFrame9838Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget/generated/GeneratedCopyrightbyakaResidentWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget/generated/GeneratedStatusBarBaseDarkWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget/generated/GeneratedModeLightTypeNumericWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget/generated/GeneratedMaskGroupWidget16.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget/generated/GeneratedGroup9818Widget1.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotpwidget/generated/GeneratedGilimWidget.dart';

/* Frame Sign in / OTP
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninOTPWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 194.0,
                child: GeneratedGroup9820Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedGilimWidget(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget14(),
              ),
              Positioned(
                left: 76.0,
                top: 115.2080078125,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget16(),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget2(),
              ),
              Positioned(
                left: 48.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 0.00002522498652979266,
                child: GeneratedGroup9818Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 51.0,
                child: GeneratedFrame9838Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedModeLightTypeNumericWidget(),
              )
            ]),
      ),
    ));
  }
}
