import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsplashscreenwidget2/generated/GeneratedStatusBarBaseDarkWidget29.dart';
import 'package:flutterapp/project_20teamapp/generatedsplashscreenwidget2/generated/GeneratedMaskGroupWidget64.dart';
import 'package:flutterapp/project_20teamapp/generatedsplashscreenwidget2/generated/GeneratedImage7Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatedsplashscreenwidget2/generated/GeneratedCopyrightbyakaResidentWidget22.dart';
import 'package:flutterapp/project_20teamapp/generatedsplashscreenwidget2/generated/GeneratedModeLightTypeDefaultWidget61.dart';

/* Frame Splash screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashscreenWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 229, 176, 75),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedCopyrightbyakaResidentWidget22(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget29(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget61(),
              ),
              Positioned(
                left: 76.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 108.58381652832031,
                child: GeneratedMaskGroupWidget64(),
              ),
              Positioned(
                left: 117.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 276.0,
                child: GeneratedImage7Widget3(),
              )
            ]),
      ),
    ));
  }
}
