import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9857widget17/generated/GeneratedKhmphtinchWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedgroup9857widget17/generated/GeneratedLinkrightWidget52.dart';

/* Group Group 9857
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup9857Widget17 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 335.0,
      height: 24.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 154.0,
              height: 26.0,
              child: GeneratedKhmphtinchWidget5(),
            ),
            Positioned(
              left: 258.0,
              top: 2.0,
              right: null,
              bottom: null,
              width: 77.0,
              height: 20.0,
              child: GeneratedLinkrightWidget52(),
            )
          ]),
    ));
  }
}
