import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninwithwidget/generated/GeneratedButtonPrimaryBlueDefaultWidget.dart';

/* Group sign in with
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninwithWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 44.0,
      height: 44.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 44.0,
              height: 44.0,
              child: GeneratedButtonPrimaryBlueDefaultWidget(),
            )
          ]),
    ));
  }
}
