import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedGroup9836Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedBottomnavWidget29.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedMaskGroupWidget56.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedThngbokhcWidget13.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedQuantrngWidget8.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedGroup9847Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedGroup9843Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedGroup9846Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedGroup9827Widget8.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedRectangle325Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedModeLightTypeDefaultWidget56.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedGroup9844Widget2.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedThngboWidget57.dart';
import 'package:flutterapp/project_20teamapp/generatedannouncementwidget116/generated/GeneratedGroup9845Widget2.dart';

/* Frame Announcement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnnouncementWidget116 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget56(),
              ),
              Positioned(
                left: -32.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 56.0,
                child: GeneratedRectangle325Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 26.0,
                child: GeneratedThngboWidget57(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.0,
                child: GeneratedQuantrngWidget8(),
              ),
              Positioned(
                left: -16.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 56.0,
                child: GeneratedGroup9836Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 26.0,
                child: GeneratedThngbokhcWidget13(),
              ),
              Positioned(
                left: 323.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 12.0,
                child: GeneratedGroup9827Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 107.00003051757812,
                child: GeneratedGroup9843Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 107.00003051757812,
                child: GeneratedGroup9844Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 107.00003051757812,
                child: GeneratedGroup9846Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 107.00003051757812,
                child: GeneratedGroup9845Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 107.00003051757812,
                child: GeneratedGroup9847Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 70.0,
                child: GeneratedBottomnavWidget29(),
              ),
              Positioned(
                left: 310.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedMaskGroupWidget56(),
              )
            ]),
      ),
    ));
  }
}
