import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedNewsWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedAnnouncementWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedAvatarWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedModeLightTypeDefaultWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedHerobannerWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedQuicknavWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedGroup9862Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedBottomnavWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedRectangle330Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedLogoWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedAvatarWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedAnnouncementWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedCardNewsWidget1.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedLogoWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedFollowupWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedhomelongwidget/generated/GeneratedNewsWidget.dart';

/* Frame Home-long
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomelongWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1831.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1831.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 389.0,
                              child: GeneratedRectangle330Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 606.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 181.0,
                              child: GeneratedNewsWidget(),
                            ),
                            Positioned(
                              left: -393.0,
                              top: 641.0,
                              right: null,
                              bottom: null,
                              width: 1162.0,
                              height: 652.0,
                              child: GeneratedNewsWidget2(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 342.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 76.0,
                              child: GeneratedQuicknavWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 24.0,
                              child: GeneratedAnnouncementWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1761.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 70.0,
                              child: GeneratedBottomnavWidget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 1580.0,
                              right: null,
                              bottom: null,
                              width: 256.8018798828125,
                              height: 146.0,
                              child: GeneratedGroup9862Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1150.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 405.0,
                              child: GeneratedFollowupWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 470.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 120.0,
                              child: GeneratedAnnouncementWidget4(),
                            ),
                            Positioned(
                              left: 349.0,
                              top: 848.0,
                              right: null,
                              bottom: null,
                              width: 313.0,
                              height: 278.0,
                              child: GeneratedCardNewsWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 210.0,
                              child: GeneratedHerobannerWidget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 37.83237075805664,
                              child: GeneratedLogoWidget1(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedAvatarWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child: GeneratedModeLightTypeDefaultWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
