import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedGroupWidget48.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedOvalWidget15.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedGroupCopy6Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedGroupCopyWidget2.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedGroupCopy3Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedGroupCopy2Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedGroup6CopyWidget.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedGroup6Copy3Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedGroupCopy5Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedGroup6Copy2Widget.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedFrameWidget64.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedTabstab1Widget5.dart';
import 'package:flutterapp/project_20teamapp/generatedserviceswidget/generated/GeneratedDchvWidget40.dart';

/* Frame Services
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedServicesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 163.0,
                child: GeneratedGroupWidget48(),
              ),
              Positioned(
                left: 196.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 163.0,
                child: GeneratedGroupCopyWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 163.0,
                child: GeneratedGroupCopy3Widget(),
              ),
              Positioned(
                left: 196.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 163.0,
                child: GeneratedGroupCopy2Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 163.0,
                child: GeneratedGroupCopy5Widget(),
              ),
              Positioned(
                left: 196.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 163.0,
                child: GeneratedGroupCopy6Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 41.0,
                child: GeneratedDchvWidget40(),
              ),
              Positioned(
                left: 302.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 61.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 61.0,
                child: GeneratedGroup6CopyWidget(),
              ),
              Positioned(
                left: 212.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 61.0,
                child: GeneratedGroup6Copy2Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 61.0,
                child: GeneratedGroup6Copy3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 84.0,
                child: GeneratedTabstab1Widget5(),
              ),
              Positioned(
                left: 323.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedOvalWidget15(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedFrameWidget64(),
              )
            ]),
      ),
    ));
  }
}
