import 'package:flutter/material.dart';

/* Rectangle image 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage5Widget47 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 408.0,
      height: 864.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/e47d114e4cc09a55e4ea9f18f0b650490ae1036c.png",
          color: null,
          fit: BoxFit.cover,
          width: 408.0,
          height: 864.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
