import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedThngboWidget84.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedComponentsnotificationcopy4Widget.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedComponentsnotificationcopy2Widget.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedTabstab1Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedGroupWidget43.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedGroup3Widget3.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedGroup2Widget19.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedOvalWidget7.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedComponentsnotificationcopyWidget.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedComponentsnotificationWidget.dart';
import 'package:flutterapp/project_20teamapp/generatednotificationswidget/generated/GeneratedFrameWidget62.dart';

/* Frame Notifications
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotificationsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 41.0,
                child: GeneratedThngboWidget84(),
              ),
              Positioned(
                left: 0.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 35.0,
                child: GeneratedGroup3Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 121.0,
                child: GeneratedComponentsnotificationcopy4Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 121.0,
                child: GeneratedComponentsnotificationWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 121.0,
                child: GeneratedComponentsnotificationcopyWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 121.0,
                child: GeneratedComponentsnotificationcopy2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 35.0,
                child: GeneratedGroup2Widget19(),
              ),
              Positioned(
                left: 0.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 35.0,
                child: GeneratedGroupWidget43(),
              ),
              Positioned(
                left: 0.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 84.0,
                child: GeneratedTabstab1Widget3(),
              ),
              Positioned(
                left: 323.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedOvalWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedFrameWidget62(),
              )
            ]),
      ),
    ));
  }
}
