import 'package:flutter/material.dart';

/* Rectangle Rectangle 333
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle333Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 150.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          color: Color.fromARGB(255, 241, 241, 241),
        ),
      ),
    ));
  }
}
