import 'package:flutter/material.dart';

/* Text đăng kí as a guest: nhập số đt >> mapping với hệ thống >> screen [đăng kí as a guest] >> info + sđt >> gửi OTP >> Nhập OTP >> New pincode >> confirm pincode >> trang chủ.
    Autogenerated by FlutLab FTF Generator
  */
class Generatedngkasaguestnhpstmappingvihthngscreenngkasaguestinfostgi
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''đăng kí as a guest:
nhập số đt >> mapping với hệ thống >> screen [đăng kí as a guest] >> info + sđt >> gửi OTP >> Nhập OTP >> New pincode >> confirm pincode >> trang chủ.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.3333333333333333,
        fontSize: 30.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
