import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedmaskgroupwidget34/generated/GeneratedRectangle329Widget10.dart';

/* Group Mask Group
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMaskGroupWidget34 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 2061.9508743286133,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 493.0751953125,
                    height: 1075.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 493.0751953125,
                            height: 1075.0,
                            child: GeneratedRectangle329Widget10(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
