import 'package:flutter/material.dart';

/* Rectangle image 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage3Widget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 384.0,
      height: 807.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/03194e19303e7fd199eeb78bd12f2c590a34cc02.png",
          color: null,
          fit: BoxFit.cover,
          width: 384.0,
          height: 807.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
