import 'package:flutter/material.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget1/generated/GeneratedGilimWidget4.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget1/generated/GeneratedFooterWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget1/generated/GeneratedStatusBarBaseDarkWidget17.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget1/generated/GeneratedComponent8Widget4.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget1/generated/GeneratedModeLightTypeDefaultWidget39.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget1/generated/GeneratedMain1Widget10.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget1/generated/Generated6numberiputWidget5.dart';
import 'package:flutterapp/project_20teamapp/generatedsigninotporiginalwidget1/generated/GeneratedGroup9820Widget8.dart';

/* Frame Sign in / OTP original
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninOTPoriginalWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 206.0,
                child: GeneratedGroup9820Widget8(),
              ),
              Positioned(
                left: 48.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 26.0,
                child: GeneratedGilimWidget4(),
              ),
              Positioned(
                left: -3198.0,
                top: -101.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 67.0,
                child: GeneratedStatusBarBaseDarkWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedModeLightTypeDefaultWidget39(),
              ),
              Positioned(
                left: 90.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 100.0,
                child: GeneratedMain1Widget10(),
              ),
              Positioned(
                left: 48.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 50.0,
                child: Generated6numberiputWidget5(),
              ),
              Positioned(
                left: 48.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 63.999996185302734,
                child: GeneratedFooterWidget5(),
              ),
              Positioned(
                left: 14.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 24.0,
                child: GeneratedComponent8Widget4(),
              )
            ]),
      ),
    ));
  }
}
