import 'package:flutter/material.dart';

/* Instance bottom nav
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBottomnavWidget25 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 70.0,
    ));
  }
}
