import 'package:flutter/material.dart';

/* Text aka
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAkaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''aka''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 0.8,
        fontSize: 30.0,
        fontFamily: 'Be Vietnam',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
