import 'package:flutter/material.dart';

/* Text Quên mật khẩu?
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQunmtkhuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Quên mật khẩu?''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.7142857142857142,
        fontSize: 14.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 63, 63, 63),
        decoration: TextDecoration.underline,
        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
